In [1]:
"""
    构造一个没有任何参数的自定义层
"""
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [2]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

Y = net(torch.rand(4, 8))
Y.mean()

tensor(-4.6566e-09, grad_fn=<MeanBackward0>)

In [3]:
# 带参数的图层
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units, ))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

dense = MyLinear(5, 3)
dense.weight

Parameter containing:
tensor([[ 0.2330, -0.5387,  1.9847],
        [ 0.2383,  0.8739, -0.3772],
        [ 0.2465,  0.4499,  1.8026],
        [-0.2132, -1.2860, -1.4705],
        [ 0.9165, -0.2559,  1.6407]], requires_grad=True)

In [4]:
# 使用自定义层直接执行正向传播计算
dense(torch.rand(2, 5))

tensor([[0.0000, 0.0000, 2.3927],
        [0.0000, 0.0000, 0.1943]])

In [5]:
# 使用自定义层构建模型
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[4.9573],
        [9.3577]])