In [32]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x ** y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [33]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [34]:
x[3] # 下标访问

tensor(3)

In [35]:
len(x) # 长度

4

In [36]:
x.shape # 形状

torch.Size([4])

In [37]:
# 创建一个矩阵
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [38]:
# 矩阵的转置
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [39]:
# 对于对称矩阵 转置等于自己
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [40]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [41]:
# 可以构建更多维的数据结构
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [42]:
# 两个相同形状的任何两个张量，结果都是相同形状的张量
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone() # clone 会分配新内存
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [43]:
A * B # 按元素相乘

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [44]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [45]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [46]:
# 计算和
# A = torch.arange(20 * 2).reshape(2, 5, 4)
# A.shape, A.sum()

In [47]:
# 指定求和汇总张量的轴
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [48]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [49]:
A.sum(axis=[0, 1]) # 等价于 A.sum()

tensor(190.)

In [50]:
# 求平均值（mean 或 average）
# A = A.float()
A.mean(), A.sum() / A.numel()

(tensor(9.5000), tensor(9.5000))

In [51]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [52]:
sum_A = A.sum(axis=1, keepdims=True) # 保留维度
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [53]:
A / sum_A # 利用广播将A除以sum_A（如果不保留维度就不能用 广播 了）

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [54]:
print(A)
A.cumsum(axis=0) # 累加求和

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [55]:
# 点积是相同位置的元素乘积的和
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [56]:
# 也可以用 乘法 再 求和，和上面等价
torch.sum(x * y)

tensor(6.)

In [57]:
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [58]:
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [59]:
'''
    L2 范数是向量元素平方和的平方根
'''
u = torch.tensor([3.0, -4.0])
print(u)
torch.norm(u)

tensor([ 3., -4.])


tensor(5.)

In [60]:
'''
    L1 范数是向量每个元素的绝对值之和
'''
torch.abs(u).sum()

tensor(7.)

In [61]:
'''
    矩阵最常用的 弗罗贝尼乌斯范数（Frobenius norm）是矩阵元素的平方和的平方根
'''
torch.norm(torch.ones((4, 9)))

tensor(6.)